schedules:
- cron: '0 0 * * 4'
  displayName: weekly build
  branches:
    include:
    - deploy
  always: true

jobs:
- job: main
  pool:
    vmImage: 'ubuntu-latest'
  timeoutInMinutes: 90
  steps:
    - script: |
        docker pull lazka/pgi-docgen:v2
      displayName: Pull Docker image
      condition: and(succeeded(), not(eq(variables['build.sourceBranch'], 'refs/heads/deploy')))
    - script: |
        cd docker
        bash -x ./build-image.sh
      displayName: Build Docker image
      condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/deploy'))
    - script: |
        cd docker
        bash -x ./test.sh
      displayName: Run Tests
      env:
        CODECOV_TOKEN: $(CODECOV_TOKEN)
    - script: |
        cd docker
        bash -x ./build-docs.sh
      displayName: Build Docs
      condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/deploy'))
    - script: |
        cd docker
        bash -x ./build-docs-sphinx.sh
      displayName: Sphinx Build
      condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/deploy'))
    - task: DownloadSecureFile@1
      inputs:
        secureFile: deploy_key
      displayName: 'Deploy Key'
      condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/deploy'))
    - script: |
        git config --global user.name "Christoph Reiter"
        git config --global user.email "reiter.christoph@gmail.com"
        mkdir ~/.ssh && mv $DOWNLOADSECUREFILE_SECUREFILEPATH ~/.ssh/id_rsa
        chmod 700 ~/.ssh && chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
      displayName: GitHub Setup
      condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/deploy'))
    - script: |
        bash -x ./tools/push.sh
      displayName: Publish Docs
      condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/deploy'))
